POST http://localhost:3002/feed/like/6867848761d31e71250c64a6
Content-Type : application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODY2N2NmMjRlZTUwYmMyNjc1YjM3MjgiLCJlbWFpbCI6InByaXlhbmthQGdtYWlsLmNvbSIsImlhdCI6MTc1MTYyNTQyOCwiZXhwIjoxNzUxNjI5MDI4fQ.dyEM9Fth8p9KjC1EaZaE1OZsvcC_iGi_EtxR4YlRjVo