GET http://localhost:3002/feed/me
Content-Type : application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODY2N2NmMjRlZTUwYmMyNjc1YjM3MjgiLCJlbWFpbCI6InByaXlhbmthQGdtYWlsLmNvbSIsImlhdCI6MTc1MTYyMDQ3NywiZXhwIjoxNzUxNjI0MDc3fQ.NfHvDoFYj4DJ0saZIGQcf2BnWTO0vQw1lIcVLUiwyJY