GET http://localhost:3002/cycle/getAll?month=7&year=2025
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODY2N2NmMjRlZTUwYmMyNjc1YjM3MjgiLCJlbWFpbCI6InByaXlhbmthQGdtYWlsLmNvbSIsImlhdCI6MTc1MTY5NDA5MywiZXhwIjoxNzUxNjk3NjkzfQ.j9BmKISzsGcAtMsvKE0CAtqkOANgoWlGMOnj55NApJI
