GET http://localhost:3002/cycle/getNext
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODY2N2NmMjRlZTUwYmMyNjc1YjM3MjgiLCJlbWFpbCI6InByaXlhbmthQGdtYWlsLmNvbSIsImlhdCI6MTc1MTgwNzkwOCwiZXhwIjoxNzUxODExNTA4fQ.O68fN3o4Lrg9SJrMoULtNeP03NGTXTnKGjpJlqFq9U8